# -*- coding: utf-8 -*-
"""wordcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kqCJCcsXwAIXpndLFeInPXx8QZo2lK-
"""

# exercice 1
# author: Bousselmi (your name)
# state : ongoing

# exercice 2
# author: BW
# state : ongoing

# exercice 3
# author: Ba
# state : ongoing