# -*- coding: utf-8 -*-
"""Wordcloud-g2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPVM8Kd92XGkw6OKGC7bfifceHkGXxY8
"""

# exercice 1
# author first member
# state: ongoing

# print(data)



# exercice 2
# author WB
# state: ongoing
!pip install pillow
import numpy as np 
from PIL import Image,ImageOps
import matplotlib.pyplot as plt
from wordcloud import WordCloud,STOPWORDS,ImageColorGenerator
from scipy.ndimage import gaussian_gradient_magnitude 

# Download the Shakespeare text from the desktop
file=open("desktop/WC/romeo.txt",'r')
text=file.read()

# Create the WordCloud
canvas_ _____=1920
canvas_ ____=1080 



# exercice 3
# author AB
# state: ongoing

#...
