# -*- coding: utf-8 -*-
"""Wordcloud-g2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPVM8Kd92XGkw6OKGC7bfifceHkGXxY8
"""

# exercice 1
# author first member
# state: ongoing

# exercice 2
# author WB
# state: ongoing

# exercice 3
# author AB
# state: ongoing

#...